[build]
  command = "python -m pip install --upgrade pip && python -m pip install -r requirements.txt"
  publish = "CODE/FRONT END/static"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9.16"
  NODE_VERSION = "16"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"
  PYTHONUNBUFFERED = "true"
  PIPENV_RUN_BIN = "/opt/buildhome/.local/bin/pipenv"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-functions-install-core"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
