[build]
  command = ""
  publish = "CODE/FRONT END/templates"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  FLASK_APP = "CODE/FRONT END/app.py"
  FLASK_ENV = "production"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
