services:
  - type: web
    name: lung-cancer-prediction
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_APP
        value: "CODE/FRONT END/app.py"
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"
